# Generated by Django 5.0.2 on 2024-02-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_name_snack_title_snack_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='snack',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]